CREATE DATABASE BD_PI
USE BD_PI

CREATE TABLE Cliente(
IdCliente INT PRIMARY KEY NOT NULL,
Nome VARCHAR(100) NOT NULL,
RG VARCHAR(20) NOT NULL,
CPF VARCHAR(14) NOT NULL,
Telefone VARCHAR(20) NOT NULL,
Email VARCHAR(100) NOT NULL,
CEP VARCHAR(9) NOT NULL,
Estado VARCHAR(20) NOT NULL,
Cidade VARCHAR(30) NOT NULL,
Rua VARCHAR(100) NOT NULL,
Bairro VARCHAR(50) NOT NULL,
NumCasa INT
)
CREATE TABLE Funcionario(
IdFuncionario INT PRIMARY KEY NOT NULL,
Cargo VARCHAR(12),
Nome VARCHAR(100) NOT NULL,
CPF VARCHAR(14) NOT NULL,
CNH VARCHAR(20),
Telefone VARCHAR(20) NOT NULL,
Email VARCHAR(100) NOT NULL,
Senha VARCHAR (20) NOT NULL, 
Funcao VARCHAR (30) NOT NULL,
CEP VARCHAR(9) NOT NULL,
Estado VARCHAR(20) NOT NULL,
Cidade VARCHAR(30) NOT NULL,
Rua VARCHAR(100) NOT NULL,
Bairro VARCHAR(50) NOT NULL,
NumCasa INT
)

CREATE TABLE Pedido(
IdPedido INT PRIMARY KEY NOT NULL,
IdCliente INT,
IdFuncionario INT,
DataPedido DATE NOT NULL,
StatusPedido CHAR(20)NOT NULL,
Total MONEY NOT NULL
FOREIGN KEY (IdCliente) REFERENCES Cliente(IdCliente),
FOREIGN KEY (IdFuncionario) REFERENCES Funcionario (IdFuncionario)
)
CREATE TABLE Produto(
IdProduto INT PRIMARY KEY NOT NULL,
Nome CHAR(20) NOT NULL,
Preco MONEY NOT NULL,
QuantidadeEstoque INT NOT NULL
)
CREATE TABLE Item_Pedido(
IdItemPedido INT PRIMARY KEY NOT NULL,
IdPedido INT NOT NULL,
IdProduto INT NOT NULL,
QuantidadePedida DECIMAL (10,2) NOT NULL,
FOREIGN KEY (IdPedido) REFERENCES Pedido(IdPedido),
FOREIGN KEY (IdProduto) REFERENCES Produto(IdProduto)
)
CREATE TABLE Pagamento(
IdPagamento INT PRIMARY KEY NOT NULL,
IdPedido INT NOT NULL,
Valor MONEY NOT NULL,
DataPagamento DATE NOT NULL,
Metodo VARCHAR(10) NOT NULL,
FOREIGN KEY (IdPedido) REFERENCES Pedido(IdPedido)
)
CREATE TABLE Entrega(
IdEntrega INT PRIMARY KEY NOT NULL,
IdPedido INT NOT NULL,
StatusEntrega VARCHAR(20) NOT NULL,
DataEntrega DATE NOT NULL,
FOREIGN KEY (IdPedido) REFERENCES Pedido(IdPedido)
)
CREATE TABLE Parcelas(
IdParcela INT PRIMARY KEY NOT NULL,
IdPagamento INT NOT NULL,
ValorParcela MONEY NOT NULL,
Quantidade INT NOT NULL,
FOREIGN KEY (IdPagamento) REFERENCES Pagamento(IdPagamento)
)

SELECT * FROM Cliente
